defmodule Rfx.Changelist do

  @moduledoc """
  Contains helper functions that operate on changelist.  

  A changelist is a list of Rfx.Changereq.structs, generated by an Rfx
  Operation.
  """

  alias Rfx.Changereq

  def to_patch(changelist) do
    changelist
    |> Enum.map(&Changereq.to_patch(&1))
  end

  def to_string([change]) do
    change |> Changereq.to_string()
  end

  def to_string(_) do
    raise "to_string only works on atomic changes"
  end

  def to_json(changelist) do
    changelist
    |> Enum.map(&Changereq.to_json(&1))
  end

  def to_lsp(changelist) do
    changelist
    |> Enum.map(&Changereq.to_lsp(&1))
  end

  def apply!(changelist) do
    changelist
    |> Enum.map(&Changereq.apply!(&1))
  end

end
