defmodule Rfx.Change.List do

  @moduledoc """
  Contains helper functions that operate on changelist.  

  A changelist is a list of Rfx.Change.Req.structs, generated by an Rfx
  Operation.
  """

  alias Rfx.Change

  def to_string(changelist) do
    changelist 
    |> Enum.map(&Change.Req.to_string/1)
  end

  def apply!(changelist) do
    changelist
    |> Enum.map(&Change.Req.apply!(&1))
  end

end
